export const FETCH_COMMENTS_FOR_ARTICLE = 'FETCH_COMMENTS_FOR_ARTICLE';
export const FETCH_COMMENTS_FAILED = 'FETCH_COMMENTS_FAILED';
export const FETCH_COMMENTS_SUCCEEDED = 'FETCH_COMMENTS_SUCCEEDED';
export const RESET_COMMENTS = 'RESET_COMMENTS';
